_wandb:
    value:
        cli_version: 0.23.1
        e:
            6zl7kynbvrhpgdg8q42z5qtcwrnmdd3h:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "5368709120"
                args:
                    - --config
                    - experiments/v1_en2vi/config.yaml
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "275008737280"
                email: nam28042004@gmail.com
                executable: /Users/maianhpham/Documents/MediTranslator/.venv/bin/python
                git:
                    commit: a25b173d9518b25d4ca95f7d616ececb5ab7e934
                    remote: https://github.com/MothMalone/MediTranslator.git
                host: Mais-MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-15.7.3-arm64-arm-64bit
                program: /Users/maianhpham/Documents/MediTranslator/scripts/train.py
                python: CPython 3.9.6
                root: /Users/maianhpham/Documents/MediTranslator
                startedAt: "2025-12-14T16:03:30.958196Z"
                writerId: 6zl7kynbvrhpgdg8q42z5qtcwrnmdd3h
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 13
                - 16
                - 61
            "4": 3.9.6
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
model:
    value:
        d_ff: 2048
        d_model: 512
        dropout: 0.1
        max_seq_length: 512
        n_decoder_layers: 6
        n_encoder_layers: 6
        n_heads: 8
training:
    value:
        batch_size: 32
        epochs: 5
        eval_every: 500
        label_smoothing: 0
        learning_rate: 0.0001
        log_every: 100
        optimizer: adam
        save_every: 20000
        scheduler: warmup
        use_wandb: true
        warmup_steps: 4000
vocab:
    value:
        min_freq: 2
        src_vocab_size: 40000
        tgt_vocab_size: 40000
